module.exports = {
	helpCmdPerPage: 10,
	lyricsMaxResults: 5,
	adminId: "UserId", 
	token: process.env.token || "", 
	clientId: process.env.clientId || "", 
	clientSecret: process.env.clientSecret || "", 
	port: process.env.PORT || 4200, 
	scopes: ["identify", "guilds", "applications.commands"], 
	inviteScopes: ["bot", "applications.commands"], 
	serverDeafen: true, 
	defaultVolume: 100, 
	supportServer: "https://discord.gg/sbySMS7m3v", 
	Issues: "https://github.com/SudhanPlayz/Discord-MusicBot/issues", 
	permissions: 277083450689, 
	disconnectTime: 30000, 
	twentyFourSeven: false, 
	autoQueue: false, 
	autoPause: true, 
	autoLeave: false, 
	debug: true, 
	cookieSecret: "CodingWithSudhan is epic", 
	website: "http://localhost:4200", 
	nodes: [
		{
			identifier: "Main Node", 
			host: process.env.LAVALINK_HOST || "lavalink.triniumhost.com", 
			port: parseInt(process.env.LAVALINK_PORT) || 4333, 
			password: process.env.LAVALINK_PASSWORD || "free", 
			retryAmount: 200, 
			retryDelay: 40, 
			secure: false, 
		},
	],
	embedColor: "#2f3136", 
	presence: {
		status: "online", 
		activities: [
			{
				name: "Music", 
				type: "LISTENING", 
			},
		],
	},
	iconURL: "https://cdn.darrennathanael.com/icons/spinning_disk.gif", 
};
